### ISSUE TITLE
Not working for current version

### ISSUE THREAD

**Issue by thunfischbrot** [lnxbil/pve-no-subscription#1]
Great time-saver for personal use!

Currently it is not working, steps to reproduce:

1. Install Proxmox 5.4.1
2. `apt-get update`
3. `apt-get dist-upgrade`
4. `git clone https://github.com/lnxbil/pve-no-subscription.git`
5. `make install`
6. Clear your browser cache
7. Log into the Proxmox web interface or select _Updates_, then _Refresh_.

Still, the _No valid subscription_ message box pops up.

![grafik](https://user-images.githubusercontent.com/583358/58458592-e826a600-8129-11e9-98db-b0860c0cd5ce.png)

**Comment by lnxbil** [comment]
Hi thunfischbrot,

This plugin is to be installed as Debian package from the release section and it works with the current `5.4-6` without any problems. Please try to install the package and report back.

For further investigation, you can also directly call the patcher:

```
$ /usr/share/pve-no-subscription/no-subscription-warning.sh
---------------[ Patching with No-Subscription-Removal-Patch ]----------------
patching file /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js
Hunk #1 succeeded at 365 (offset 12 lines).
patching file /usr/share/pve-manager/js/pvemanagerlib.js
Hunk #1 succeeded at 426 (offset 99 lines).
Hunk #2 succeeded at 36812 (offset 6871 lines).
------------------------------------------------------------------------------
```

**Comment by thunfischbrot** [comment]
Ah, thank you, that worked well! I did not manage to find the release page before.

**Comment by lnxbil** [comment]
Glad it worked.
